# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ht_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rht_data.proto\"a\n\x07ht_data\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08shock_fr\x18\x02 \x01(\x02\x12\x10\n\x08shock_fl\x18\x03 \x01(\x02\x12\x10\n\x08shock_br\x18\x04 \x01(\x02\x12\x10\n\x08shock_bl\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ht_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HT_DATA']._serialized_start=17
  _globals['_HT_DATA']._serialized_end=114
# @@protoc_insertion_point(module_scope)
